get http:localhost:3000/

### get do user
get http://localhost:3000/usuarios

### get com id filtro
get http://localhost:3000/usuarios/1

### criaruser
post http://localhost:3000/cadastro
Content-Type: application/json

{
    "nome": "Pedro",
    "email": "pedro@gmail.com"
}

### put
put http://localhost:3000/editar/1
Content-Type: application/json

{
    "nome":"João atualizado"
}

### deletar
delete http://localhost:3000/deletar/1